//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.10 at 11:00:55 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://drugbank.ca", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package drugbank.xjc20131209;
